<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_testing automate_sendbird-message-input-text-field</name>
   <tag></tag>
   <elementGuidId>d6e8445c-87f0-45b9-aa5e-d15d0e3ffee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sendbird-message-input-text-field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sendbird-message-input-text-field</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'sendbird-message-input-text-field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8fdcd801-cee2-4853-bb12-7b805019b92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sendbird-message-input-text-field</value>
      <webElementGuid>9eb77039-ec75-4b23-a164-a0c6bf03f56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sendbird-message-input--textarea sendbird-message-input-text-field</value>
      <webElementGuid>36fc6046-9b7f-4222-8108-0e6a9a6efdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>35aeb737-a4cf-4683-8fa5-ab7fd4c8305d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>dd2c398e-9f47-4575-8460-92ebe0b6154b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Text Input</value>
      <webElementGuid>e71aa987-a62c-450b-8ab4-79c3939078fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>16f08031-0291-4591-8df1-563e521c84fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sendbird-message-input-text-field&quot;)</value>
      <webElementGuid>b49524cb-b00d-4f74-84c7-ed515ecf45a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='sendbird-message-input-text-field']</value>
      <webElementGuid>77999152-541a-4519-8460-a1918df2cfa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div[3]/div/form/div/div</value>
      <webElementGuid>2e0f9a81-aad5-436d-aa2b-d0f286338c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>42bbdb11-a9c2-4621-8c33-dfc80ef9c03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'sendbird-message-input-text-field']</value>
      <webElementGuid>44b53465-74a0-4f78-86f0-ed8ee272f832</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
