<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_testing automate_sendbird-message-input-text-field</name>
   <tag></tag>
   <elementGuidId>fc49bc93-0bc5-461c-a92e-e133a98662f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sendbird-message-input-text-field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sendbird-message-input-text-field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>341b94b9-20a4-4be8-a67a-0dcc5f3f3bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sendbird-message-input-text-field</value>
      <webElementGuid>19c3897f-60e8-4274-8d29-131ed9815876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sendbird-message-input--textarea sendbird-message-input-text-field</value>
      <webElementGuid>12e1ec39-125d-497d-b7fc-eae0723ca5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>25955161-61bc-4c1c-b7cc-1479f3d9acab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>4a111c0b-ea23-404b-8760-69a1e1b5ad2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Text Input</value>
      <webElementGuid>92e4bcc6-c417-4b77-a8d7-ba7c54da045d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>42383aa9-26df-4036-b8ed-70ec9686fb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sendbird-message-input-text-field&quot;)</value>
      <webElementGuid>b7a52d3e-a4a1-440f-8a49-0004e40e218d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='sendbird-message-input-text-field']</value>
      <webElementGuid>ed234d86-3a6c-43b1-baf9-c1578840afb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div[2]/div/div[3]/div/form/div/div</value>
      <webElementGuid>96d7f6a6-e874-4776-8e2d-97ef886bb687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>37f2e89c-ef07-4907-81c5-e0c4680fc67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'sendbird-message-input-text-field']</value>
      <webElementGuid>8da1c214-36c7-4b56-9c33-7f2c9b6eea98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
