<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Frame_1718601019963</name>
   <tag></tag>
   <elementGuidId>0a4a72c9-0ec8-460d-a429-133f4bdf72ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>IFRAME</value>
      <webElementGuid>3b7017e9-340e-4169-96e4-b911ee2ac4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1718601019963</value>
      <webElementGuid>7144c6a8-4212-48c8-ab3f-ded1c664bcb1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
